#!/usr/bin/env bash
# Re-download the three self-hosted faces (design spec §4) as latin-subset
# woff2 into public/fonts, and regenerate public/fonts/fonts.css.
#
# Google's CSS endpoint serves ttf to unknown user agents and woff2 only to
# browsers it recognises, hence the UA below. Run from the repo root.
set -euo pipefail
cd "$(dirname "$0")/.."
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
mkdir -p public/fonts && cd public/fonts

for spec in "Bricolage+Grotesque:wght@600;700|bricolage" \
            "Instrument+Sans:wght@400;500;600|instrument" \
            "IBM+Plex+Mono:wght@400;500|plexmono"; do
  curl -sS --max-time 25 -A "$UA" \
    "https://fonts.googleapis.com/css2?family=${spec%%|*}&display=swap" \
    -o "${spec##*|}.css"
done

python3 - <<'PY'
import re, os, subprocess
UA = os.environ.get("UA", "Mozilla/5.0")
faces = []
for slug in ["bricolage", "instrument", "plexmono"]:
    for block in re.findall(r"@font-face\s*\{[^}]*\}", open(f"{slug}.css").read()):
        rng = re.search(r"unicode-range:\s*([^;]+);", block)
        if not rng or "U+0000-00FF" not in rng.group(1):
            continue  # latin only; skip cyrillic/greek/vietnamese/latin-ext
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        wt = re.search(r"font-weight:\s*(\d+)", block).group(1)
        url = re.search(r"url\((https[^)]+)\)", block).group(1)
        name = f"{slug}-{wt}.woff2"
        faces.append((fam, wt, name, rng.group(1).strip()))
        subprocess.run(["curl","-sS","--max-time","30","-A",UA,url,"-o",name], check=True)

out = ["/* Self-hosted latin subsets — design spec §4.",
       "   Regenerated by scripts/fetch-fonts.sh. No font CDN at runtime. */", ""]
for fam, wt, name, rng in faces:
    out.append(f"@font-face {{\n  font-family: '{fam}';\n  font-style: normal;\n"
               f"  font-weight: {wt};\n  font-display: swap;\n"
               f"  src: url('/fonts/{name}') format('woff2');\n"
               f"  unicode-range: {rng};\n}}")
open("../../src/fonts.css","w").write("\n".join(out) + "\n")
for f in ["bricolage.css","instrument.css","plexmono.css"]: os.remove(f)
print(f"{len(faces)} faces written")
PY
